export const dummyFoodDatabase = [
  {
    id: "1",
    name: "Grilled Chicken Breast",
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    sugar: 0,
    servingSize: "100g",
    image: "/placeholder.svg?height=48&width=48",
  },
  {
    id: "2",
    name: "Brown Rice",
    calories: 112,
    protein: 2.6,
    carbs: 23.5,
    fat: 0.9,
    sugar: 0.4,
    servingSize: "100g",
    image: "/placeholder.svg?height=48&width=48",
  },
  {
    id: "3",
    name: "Avocado",
    calories: 160,
    protein: 2,
    carbs: 8.5,
    fat: 14.7,
    sugar: 0.7,
    servingSize: "100g",
    image: "/placeholder.svg?height=48&width=48",
  },
  {
    id: "4",
    name: "Salmon Fillet",
    calories: 208,
    protein: 20,
    carbs: 0,
    fat: 13,
    sugar: 0,
    servingSize: "100g",
    image: "/placeholder.svg?height=48&width=48",
  },
  {
    id: "5",
    name: "Greek Yogurt",
    calories: 59,
    protein: 10,
    carbs: 3.6,
    fat: 0.4,
    sugar: 3.2,
    servingSize: "100g",
    image: "/placeholder.svg?height=48&width=48",
  },
  {
    id: "6",
    name: "Banana",
    calories: 89,
    protein: 1.1,
    carbs: 22.8,
    fat: 0.3,
    sugar: 12.2,
    servingSize: "100g",
    image: "/placeholder.svg?height=48&width=48",
  },
  {
    id: "7",
    name: "Spinach",
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    sugar: 0.4,
    servingSize: "100g",
    image: "/placeholder.svg?height=48&width=48",
  },
  {
    id: "8",
    name: "Almonds",
    calories: 579,
    protein: 21.2,
    carbs: 21.7,
    fat: 49.9,
    sugar: 4.2,
    servingSize: "100g",
    image: "/placeholder.svg?height=48&width=48",
  },
  {
    id: "9",
    name: "Sweet Potato",
    calories: 86,
    protein: 1.6,
    carbs: 20.1,
    fat: 0.1,
    sugar: 4.2,
    servingSize: "100g",
    image: "/placeholder.svg?height=48&width=48",
  },
  {
    id: "10",
    name: "Egg",
    calories: 155,
    protein: 12.6,
    carbs: 1.1,
    fat: 10.6,
    sugar: 1.1,
    servingSize: "100g",
    image: "/placeholder.svg?height=48&width=48",
  },
]

export const dummyFoodEntries = [
  {
    id: "entry1",
    name: "Grilled Chicken Breast",
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    sugar: 0,
    servingSize: "100g",
    mealType: "Lunch",
    image: "/placeholder.svg?height=48&width=48",
  },
  {
    id: "entry2",
    name: "Brown Rice",
    calories: 112,
    protein: 2.6,
    carbs: 23.5,
    fat: 0.9,
    sugar: 0.4,
    servingSize: "100g",
    mealType: "Lunch",
    image: "/placeholder.svg?height=48&width=48",
  },
  {
    id: "entry3",
    name: "Greek Yogurt",
    calories: 59,
    protein: 10,
    carbs: 3.6,
    fat: 0.4,
    sugar: 3.2,
    servingSize: "100g",
    mealType: "Breakfast",
    image: "/placeholder.svg?height=48&width=48",
  },
  {
    id: "entry4",
    name: "Banana",
    calories: 89,
    protein: 1.1,
    carbs: 22.8,
    fat: 0.3,
    sugar: 12.2,
    servingSize: "100g",
    mealType: "Breakfast",
    image: "/placeholder.svg?height=48&width=48",
  },
  {
    id: "entry5",
    name: "Almonds",
    calories: 145,
    protein: 5.3,
    carbs: 5.4,
    fat: 12.5,
    sugar: 1.1,
    servingSize: "25g",
    mealType: "Snacks",
    image: "/placeholder.svg?height=48&width=48",
  },
]

